In [2]:
import pandas as pd
import requests
import time
import os

In [3]:
districts = {
    "Ahmednagar": (19.0952, 74.7496),
    "Pune": (18.5204, 73.8567),
    "Nashik": (19.9975, 73.7898),
    "Solapur": (17.6599, 75.9064),
    "Nagpur": (21.1458, 79.0882),
    "Kolhapur": (16.7050, 74.2433),
    "Sangli": (16.8524, 74.5815),
    "Satara": (17.6805, 74.0183),
    "Jalgaon": (21.0077, 75.5626),
    "Chhatrapati Sambhajinagar": (19.8762, 75.3433)
}

In [4]:
START_DATE = "2023-01-01"
END_DATE = "2025-12-31"

In [5]:
weather_data = []

for district, (lat, lon) in districts.items():

    print(f"Downloading : {district}")

    url = (
        "https://archive-api.open-meteo.com/v1/archive"
        f"?latitude={lat}"
        f"&longitude={lon}"
        f"&start_date={START_DATE}"
        f"&end_date={END_DATE}"
        "&daily="
        "temperature_2m_max,"
        "temperature_2m_min,"
        "precipitation_sum,"
        "rain_sum,"
        "windspeed_10m_max"
        "&timezone=Asia/Kolkata"
    )

    response = requests.get(url)

    if response.status_code != 200:
        print("Failed :", district)
        continue

    data = response.json()

    daily = data["daily"]

    df = pd.DataFrame({

        "Date": daily["time"],

        "District": district,

        "Max_Temp": daily["temperature_2m_max"],

        "Min_Temp": daily["temperature_2m_min"],

        "Rainfall_mm": daily["precipitation_sum"],

        "Rain_mm": daily["rain_sum"],

        "WindSpeed": daily["windspeed_10m_max"]

    })

    weather_data.append(df)

    time.sleep(1)

print("Download Completed")

Downloading : Ahmednagar
Downloading : Pune
Downloading : Nashik
Downloading : Solapur
Downloading : Nagpur
Downloading : Kolhapur
Downloading : Sangli
Downloading : Satara
Downloading : Jalgaon
Downloading : Chhatrapati Sambhajinagar
Download Completed

In [6]:
weather_df = pd.concat(
    weather_data,
    ignore_index=True
)

weather_df.head()

         Date    District  Max_Temp  Min_Temp  Rainfall_mm  Rain_mm  WindSpeed
0  2023-01-01  Ahmednagar      28.9      14.3          0.0      0.0       14.5
1  2023-01-02  Ahmednagar      28.7      14.4          0.0      0.0       11.4
2  2023-01-03  Ahmednagar      28.5      14.3          0.0      0.0       10.9
3  2023-01-04  Ahmednagar      28.6      15.2          0.0      0.0       16.6
4  2023-01-05  Ahmednagar      27.7      17.6          0.1      0.1       19.0

In [7]:
weather_df.shape

(10960, 7)

In [8]:
os.makedirs("../data/external", exist_ok=True)

weather_df.to_csv(
    "../data/external/weather_maharashtra_2023_2025.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [9]:
weather_df.sample(10)

,Date,District,Max_Temp,Min_Temp,Rainfall_mm,Rain_mm,WindSpeed
110,2023-04-21,Ahmednagar,36.5,22.3,0.0,0.0,24.5
5862,2024-01-18,Kolhapur,29.1,15.9,0.0,0.0,12.0
7840,2023-06-18,Satara,31.0,23.3,0.5,0.5,21.1
7476,2025-06-19,Sangli,27.3,22.5,8.3,8.3,27.4
9366,2024-08-21,Jalgaon,30.6,24.2,21.0,21.0,11.5
7846,2023-06-24,Satara,30.2,23.3,8.1,8.1,17.3
5048,2024-10-26,Nagpur,32.4,21.8,0.0,0.0,13.5
1941,2025-04-25,Pune,39.2,23.9,0.0,0.0,18.7
2305,2023-04-24,Nashik,35.5,19.8,0.0,0.0,22.8
8071,2024-02-04,Satara,31.1,16.2,0.0,0.0,10.5